### DISCUSSION TITLE
Can't reach database server

### DISCUSSION THREAD

**Discussion by VictorBuilder** [johanohly/AirTrail#212] [General]
Hi,

First off, thanks for the amazing work on this project! I'm a hobbyist trying to learn how everything fits together.

I'm attempting to deploy AirTrail using Portainer. The stack deploys successfully, and the DB container logs indicate it's running fine (`LOG: database system is ready to accept connections`). 

However, the application container fails with the following error:

```
ECONNREFUSED: Failed to connect
   errno: 103
 syscall: "connect"
      at /app/node_modules/pg-pool/index.js:45:11
Applying migrations...
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "airtrail", schema "public" at "localhost:5432"
Error: P1001: Can't reach database server at `localhost:5432`
Please make sure your database server is running at `localhost:5432`.
Starting server...
Error loading app config from .env: 40 |     res = resolve
41 |     rej = reject
42 |   }).catch((err) => {
43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
44 |     // application that created the query
45 |     Error.captureStackTrace(err)
```

I'm running another app on port 3000, so I changed the port for AirTrail to 3010.

Here's my docker-compose file:

```
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 3010:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

and my .env file:

`ORIGIN=http://localhost:3010
DB_URL=postgres://airtrail:mypass@localhost:5432/airtrail
DB_PASSWORD=mypass
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail`

Any ideas on what might be going wrong? Appreciate any help you can offer!

**Comment by johanohly** [comment]
Hi, thanks for trying out AirTrail!

The issue you're seeing is because the database container isn't exposed externally—it's accessible only within Docker Compose's internal network. Instead of connecting via `localhost`, the application should connect to the database container's internal hostname, which in your compose file is `db`.

Try changing your .env file to use:

```
DB_URL=postgres://airtrail:mypass@db:5432/airtrail
```

This should resolve the connection issue. Let me know if this helps or if you're still having trouble!

**Reply by VictorBuilder** [reply]
Hi, thanks for the quick reply!

That indeed did the trick. I initially changed it because of this comment: 
`# Change "db" to "localhost" if you are developing locally`

Unfortunately, now I'm stuck on the initial user creation screen, it just keeps loading. I've tried restarting the application, but it's always the same result. I also don't see any errors in the logs.

![Screenshot](https://github.com/user-attachments/assets/09142cd4-7c83-49a8-99fb-2c4f5e77534e)

**Reply by johanohly** [reply]
I suspect you will find an error in the browser inspector console — right click page - > inspect -> console tab.

**Reply by VictorBuilder** [reply]
There is an error, indeed.
```
POST 403 (Forbidden)
'Cross-site POST form submissions are forbidden'
```

I use Chrome.

Edit: I'm now accessing my network through VPN. Could that be the reason?

**Reply by johanohly** [reply]
This means your `ORIGIN` env var is incorrect. It has to match the origin of the url you are accessing AirTrail from. 
Using a VPN could also further mess things up, but you'll have to trial-and-error to find the correct value.

**Comment by VictorBuilder** [comment]
Hello @johanohly,

I'm getting the same error while trying to access AirTrail from my local network without VPN. 
Any suggestions?

**Reply by johanohly** [reply]
I am assuming you mean the CORS-error in the browser console. 

This is not very well documented, but you are able to provide multiple URLs in the `ORIGIN` environment variable (comma-separated), to accommodate two different entry points for example (one remote and one local).

**Reply by VictorBuilder** [reply]
What made it work for me was switching from HTTPS to HTTP.

**Comment by adamzvolanek** [comment]
Getting the same error when running my docker compose configuration. If anyone can provide any help. Maybe I am missing something obvious. Using unraid.

Error: 

```
Applying migrations...
Prisma schema loaded from prisma/schema.prisma
Error: Prisma schema validation - (get-config wasm)
Error code: P1012
error: Environment variable not found: DB_URL.
  -->  prisma/schema.prisma:3
   | 
 2 |   provider = "postgresql"
 3 |   url      = env("DB_URL")
   | 
Validation Error Count: 1
[Context: getConfig]
Prisma CLI Version : 6.6.0
Starting server...
Error loading app config from .env: 40 |     res = resolve
41 |     rej = reject
42 |   }).catch((err) => {
43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
44 |     // application that created the query
45 |     Error.captureStackTrace(err)
               ^
ECONNREFUSED: Failed to connect
   errno: 103
 syscall: "connect"
      at /app/node_modules/pg-pool/index.js:45:11
```


Compose file:

```yaml
services:
  airtrail_db:
    container_name: airtrail_db
    image: postgres:16-alpine
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:5432:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/user/appdata/airtrail/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:8468:3000"
    volumes:
      - /mnt/user/appdata/airtrail/config:/config
    depends_on:
      airtrail_db:
        condition: service_healthy
    restart: unless-stopped

networks:
  devrack:
    name: ${DOCKER_NETWORK}
    external: true
```

Environment file:

```yaml

# AirTrail Setup
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=http://localhost:8468

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the "password" part of the URL
# If you are using your own database, you should change this to the correct URL
#                          ∨∨∨∨∨∨∨∨
DB_URL=postgres://airtrail:password@airtrail_db:5432/airtrail
#                                   ∧∧
# Change "db" to "localhost" if you are developing locally

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

**Reply by adamzvolanek** [reply]
Fixed by adding the DB_URL as an environment to the airtrail container.

```yaml
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    networks:
      - devrack
    ports:
      - "${SERVER_IP}:8468:3000"
    environment:
      DB_URL: ${DB_URL}
    volumes:
      - /mnt/user/appdata/airtrail/config:/config
    depends_on:
      airtrail_db:
        condition: service_healthy
    restart: unless-stopped
```
