### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by robjae** [johanohly/AirTrail#11]
### The bug

I need to change the port as 3000 is in use.  I changed it in the .env and the docker-compose.yml files.  The containers start successfully, but when I go to the webpage, I get a 500 internal error.

### Operating System that is running AirTrail

docker

### AirTrail Version

current

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 4000:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=http://localhost:4000

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the PASSWORD_HERE
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:PASSWORD_HERE@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=PASSWORD_HERE

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1.start containers
2.try to open webpage
3.get error
...

### Relevant log output

```shell
error: password authentication failed for user "airtrail"
 code: "28P01"
      at /app/node_modules/pg-pool/index.js:45:11
      at processTicksAndRejections (native:1:1)
40 |     res = resolve
41 |     rej = reject
42 |   }).catch((err) => {
43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
44 |     // application that created the query
45 |     Error.captureStackTrace(err)
               ^
TRPCError: password authentication failed for user "airtrail"
 code: "INTERNAL_SERVER_ERROR"
      at /app/node_modules/pg-pool/index.js:45:11
      at processTicksAndRejections (native:1:1)
40 |     res = resolve
41 |     rej = reject
42 |   }).catch((err) => {
43 |     // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
44 |     // application that created the query
45 |     Error.captureStackTrace(err)
               ^
error: password authentication failed for user "airtrail"
 code: "28P01"
      at /app/node_modules/pg-pool/index.js:45:11
      at processTicksAndRejections (native:1:1)
```
