### ISSUE TITLE
Number of flights inaccurate in statistics

### ISSUE THREAD

**Issue by edbourque0** [johanohly/AirTrail#152]
### The bug

The total number of flights appearing on the top left of the statistics page is not the same as the number of flights in the flight log.
The flight log shows 52 and the statistics shows 45 in my case.

### Operating System that is running AirTrail

Docker (Portainer) on linux

### AirTrail Version

v1.1.2

### Your docker-compose.yml content

```YAML
services:
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - stack.env
    ports:
      - 41875:3000

volumes:
  db_data:
```

### Your .env content

```Shell
ORIGIN:https://flights.mydomain.com
DB_URL:postgres://username:password@10.0.0.29:62345/airtrail
```

### Reproduction steps

1. Start airtrail
2. Look at the total number of flights in the flight log
3. Look at the total number of flights in the statistics page
...
