### ISSUE TITLE
Unable to complete Setup process - Account generation doesn't complete. 

### ISSUE THREAD

**Issue by Dezrin** [johanohly/AirTrail#163]
### The bug

I am unable to create a user account to complete the setup process for AirTrail, once I click create the button throbber (technical term, I promise) just loops endlessly.

I have tried recreating the DB and the stack (running via Portainer), this has not helped. 

### Operating System that is running AirTrail

Ubuntu 22.04 LTS - Docker version 24.0.7 (standalone)

### AirTrail Version

Latest

### Your docker-compose.yml content

```YAML
services:
  db:
    image: postgres:16
    container_name: AirTrail-DB
    hostname: airtrail-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "airtrail", "-U", "airtrailuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - airtraildb:/var/lib/postgresql/data:rw
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: omitted
      POSTGRES_USER: omitted
      POSTGRES_PASSWORD: omitted
    restart: on-failure:5

  airtrail:
    image: johly/airtrail:latest
    container_name: AirTrail
    restart: on-failure:5
    environment:
      - ORIGIN=https://airtrail.omitted
      - DB_URL=postgres://omitted:omitted@omitted:5433/omitted
      - DB_DATABASE_NAME=omitted
      - DB_USERNAME=omitted
      - DB_PASSWORD=omitted
    ports:
      - 3857:3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.airtrail-secure.entrypoints=https" # This is the entry point. You can add custom ports in traefik.yaml etc
      - "traefik.http.routers.airtrail-secure.rule=Host(`airtrail.omitted`)"
      - "traefik.http.routers.airtrail-secure.service=airtrail"
      - "traefik.http.routers.airtrail-secure.tls=true" # This tells traefic your want it to get a cert and use ssl
      - "traefik.http.routers.airtrail-secure.tls.certresolver=cloudflare" # This Label is required only on the Redis hosts
      - "traefik.http.routers.airtrail-secure.service=airtrail-secure" # What show up on the Traefic Dashboard
      - "traefik.http.services.airtrail-secure.loadbalancer.server.port=omitted" # This is the port the container uses
      - 'traefik.http.routers.airtrail-secure.middlewares=realCloudflareIP@file'
    depends_on:
      db:
        condition: service_healthy

volumes:
  airtraildb:
    external: true
```

### Your .env content

```Shell
ORIGIN=https://airtrail.omitted
DB_URL=postgres://omitted:omitted@omitted:5433/omitted
DB_DATABASE_NAME=omitted
DB_USERNAME=omitted
DB_PASSWORD=omitted
PUID=0
PGID=0
```

### Reproduction steps

1. Use the above docker-compose.yml configuration in a stack within Portainer
2. Deploy the strack
3. Access the UI and attempt to complete setup
...

### Relevant log output

```shell
Applying migrations...
Resolving dependencies
Resolved, downloaded and extracted [26]
Saved lockfile
Prisma schema loaded from prisma/schema.prisma
Datasource "db": PostgreSQL database "omitted", schema "public" at "omitted:5433"
8 migrations found in prisma/migrations
Applying migration `0_init`
Applying migration `20240906191934_add_owner`
Applying migration `20240906204514_cascade_sessions_on_delete`
Applying migration `20240911144624_multi_user_flights`
Applying migration `20240925181003_oauth`
Applying migration `20241003080714_visited_countries`
Applying migration `20241006184406_icao_aircraft_codes`
Applying migration `20241108100132_app_config`
The following migration(s) have been applied:
migrations/
  └─ 0_init/
    └─ migration.sql
  └─ 20240906191934_add_owner/
    └─ migration.sql
  └─ 20240906204514_cascade_sessions_on_delete/
    └─ migration.sql
  └─ 20240911144624_multi_user_flights/
    └─ migration.sql
  └─ 20240925181003_oauth/
    └─ migration.sql
  └─ 20241003080714_visited_countries/
    └─ migration.sql
  └─ 20241006184406_icao_aircraft_codes/
    └─ migration.sql
  └─ 20241108100132_app_config/
    └─ migration.sql
      
All migrations have been successfully applied.
Starting server...
Listening on 0.0.0.0:3000
Loaded config from .env
```
