### ISSUE TITLE
Cannot find package 'geo-tz'

### ISSUE THREAD

**Issue by alexagrippin** [johanohly/AirTrail#168]
### The bug

I just saw today that watchtower updated my AirTrail and since then, it cannot be started. The logfile shows "error: Cannot find package 'geo-tz' from '/app/build/server/chunks/source.js'"

### Operating System that is running AirTrail

Linux

### AirTrail Version

v2.0.0

### Your docker-compose.yml content

```YAML
services:
  db:
    image: postgres:16
    container_name: AirTrail-DB
    hostname: airtrail-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "airtrail", "-U", "airtrailuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume4/docker/airtrail_db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrailuser
      POSTGRES_PASSWORD: airtrailpass
    restart: on-failure:5

  airtrail:
    image: johly/airtrail:latest
    container_name: AirTrail
    restart: on-failure:5
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - ORIGIN=https://airtrail.xxxx.com
      - DB_URL=postgres://airtrailuser:airtrailpass@db:5432/airtrail
      - DB_DATABASE_NAME=airtrail
      - DB_USERNAME=airtrailuser
      - DB_PASSWORD=airtrailpass
    ports:
      - 3857:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell
BUN_INSTALL_BIN	/usr/local/bin
BUN_RUNTIME_TRANSPILER_CACHE_PATH	0
PATH	/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

### Reproduction steps

1. Create YML
2. Build Container
3. Start Container

### Relevant log output

```shell
Bun v1.1.34 (Linux x64 baseline)

Applying migrations...

Prisma schema loaded from prisma/schema.prisma

Datasource "db": PostgreSQL database "airtrail", schema "public" at "db:5432"

10 migrations found in prisma/migrations

No pending migrations to apply.

Starting server...

error: Cannot find package 'geo-tz' from '/app/build/server/chunks/source.js'

Bun v1.1.34 (Linux x64 baseline)
```

### Additional information

Airtrail DB is running healthy
