### ISSUE TITLE
Flight found but no information entered

### ISSUE THREAD

**Issue by wilcochris** [johanohly/AirTrail#169]
### The bug

When trying to add a new flight by flight number, it says the flight is found and do I want to overwrite the information already there (there isn't anything). When I say yes it then says flight is found but no information is entered and it has to be entered manually.

### Operating System that is running AirTrail

Windows

### AirTrail Version

Unable to locate

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /srv/volumes/airtrail_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail_app
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3400:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
ORIGIN=https://***

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the PASSWORD_HERE
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:***@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=***

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=***
DB_USERNAME=***
```

### Reproduction steps

1. Select add flight
2. Input flight number
3. Message asks to overwrite current info (there is none)
4. Click ok
5. No information entered
6. Manually add information and then add flight
...

### Relevant log output

```shell

```
