### ISSUE TITLE
Error 500 after updating to 2.0

### ISSUE THREAD

**Issue by benjaminjonard** [johanohly/AirTrail#170]
### The bug

Hello, after updating to version 2.0.0, I have an error 500:

![Image](https://github.com/user-attachments/assets/eb7e499e-cf4b-46bb-bc7f-d6bcc621893b)

I found these messages in airtrail logs : `TypeError: null is not an object (evaluating 'flight.from.tz')`

### Operating System that is running AirTrail

Linux

### AirTrail Version

v2.0.0

### Your docker-compose.yml content

```YAML
services:
  airtrail_postgres:
    container_name: airtrail_postgres
    image: postgres:16
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      airtrail_postgres:
        condition: service_healthy
```

### Your .env content

```Shell

```

### Reproduction steps

1. Updating to v2.0.0
2. Trying to access any pages

### Relevant log output

```shell
73 |   minute: "numeric"
74 | }).format(date);
75 | const prepareFlightData = (data) => {
76 |   if (!data) return [];
77 |   return data.map((flight) => {
78 |     const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;
                                                                                        ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at /app/build/server/entries/pages/_page.svelte.js:78:84
      at map (1:11)
      at prepareFlightData (/app/build/server/entries/pages/_page.svelte.js:77:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:6594:34)
      at children (/app/build/server/chunks/internal.js:419:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11759:13)
      at Tooltip_provider (/app/build/server/chunks/MapLibre.js:6784:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11737:9)
      at slot (/app/build/server/chunks/index2.js:352:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:63:3)

749 |       if (hasStateChanged) {
750 |         this.commandState = currentState;
751 |         this.onStateChange?.current?.(snapshot(currentState));
752 |       }
753 |     });
754 |   }
                                                                                             ^
TypeError: null is not an object (evaluating 'flight.from.tz')
      at /app/build/server/entries/pages/_page.svelte.js:754:88
      at map (unknown:1:11)
      at prepareFlightData (/app/build/server/entries/pages/_page.svelte.js:77:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:6594:34)
      at children (/app/build/server/chunks/internal.js:419:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11759:13)
      at Tooltip_provider (/app/build/server/chunks/MapLibre.js:6784:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11737:9)
      at slot (/app/build/server/chunks/index2.js:352:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:63:3)
```
