### ISSUE TITLE
Visited Country Page Issue

### ISSUE THREAD

**Issue by DevGoran** [johanohly/AirTrail#177]
### The bug

Opening the Visited Country page shows following weird behaviour:

![Image](https://github.com/user-attachments/assets/7a4f798a-746d-4e6b-871b-4efb76605a3d)

### Operating System that is running AirTrail

Ubuntu Server, Docker

### AirTrail Version

2.1.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    dns: ip
    env_file:
      - stack.env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
ORIGIN=https://airtrail.domain.com
DB_URL=postgres://user:pass@db:5432/airtrail
DB_PASSWORD=pass
DB_DATABASE_NAME=user
DB_USERNAME=user
```

### Reproduction steps

1. Open Visited Countries page

### Relevant log output

```shell

```
