### ISSUE TITLE
Internal error after importing data from other AirTrail instance

### ISSUE THREAD

**Issue by MHerbst** [johanohly/AirTrail#184]
### The bug

I have exported flight data from one AirTrail instance and imported it in a newly installed AirTrail instance. Import seemed to be OK but the new instance now does no long work and only shows an "Internal error". 

It seems that the problem is caused by some older data where "departure" and "arrival" timestamps are "null". Interestingly this did not cause any problems with older versions of AirTrail.
Here is an example of the data in JSON format:

```
  "flights": [
    {
      "date": "2010-01-08",
      "from": {
        "code": "VDSR",
        "iata": null,
        "lat": 13.41155,
        "lon": 103.813044,
        "tz": "Asia/Jakarta",
        "name": "Siem Reap International Airport",
        "type": "closed",
        "continent": "AS",
        "country": "KH",
        "custom": false
      },
      "to": {
        "code": "VVTS",
        "iata": "SGN",
        "lat": 10.8188,
        "lon": 106.652,
        "tz": "Asia/Ho_Chi_Minh",
        "name": "Tan Son Nhat International Airport",
        "type": "large_airport",
        "continent": "AS",
        "country": "VN",
        "custom": false
      },
      "departure": null,
      "arrival": null,
      "duration": 3660,
      "flightNumber": null,
      "flightReason": "leisure",
      "airline": "HVN",
      "aircraft": "A319",
      "aircraftReg": null,
      "note": null,
      "seats": [
        {
          "userId": "8wra1mac2crldty",
          "guestName": null,
          "seat": null,
          "seatNumber": null,
          "seatClass": "economy"
        }
      ]
    }

```

### Operating System that is running AirTrail

Docker (Portainer) on Alpine Linux

### AirTrail Version

v2.1.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrail
      POSTGRES_PASSWORD: password
    volumes:
      - /data/compose/airtrail:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airtrail -d airtrail']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    environment:
      ORIGIN: http://192.168.2.15:3001
      DB_URL: postgres://airtrail:password@db:5432/airtrail
    ports:
      - 3001:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell

```

### Reproduction steps

1. Load exported data in JSON format
2. Refresh the Browser
3.
...

### Relevant log output

```shell
31 |   return data.map((flight) => {
32 |     const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;
33 |     return {
34 |       ...flight,
35 |       date: departure ?? parseLocal(flight.date, "yyyy-MM-dd", flight.from.tz),
36 |       departure,

TypeError: null is not an object (evaluating 'flight.from.tz')
      at /app/build/server/chunks/data.js:36:75
      at map (unknown:1:11)
      at prepareFlightData (/app/build/server/chunks/data.js:31:15)
      at _page (/app/build/server/entries/pages/_page.svelte.js:6447:34)
      at children (/app/build/server/chunks/internal.js:420:9)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11444:13)
      at Tooltip_provider (/app/build/server/chunks/MapLibre.js:6789:3)
      at children (/app/build/server/entries/pages/_layout.svelte.js:11422:9)
      at slot (/app/build/server/chunks/index2.js:352:5)
      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:69:3)^
```
