### ISSUE TITLE
sort the list of connections for a route/airport by date

### ISSUE THREAD

**Issue by evanrich** [johanohly/AirTrail#186]
### The bug

![Image](https://github.com/user-attachments/assets/5d2695f4-7407-45e1-8410-2a6c279a98b5)

these don't line up
10/15
9/25
9/29
9/28

they should be in order from either oldest to newest, or newest to oldest, that way it would make sense, since, for example, I first flew to manila from LAX, then from Manila to El nido, then from el nido back to manila, then manila back to LA.   

### Operating System that is running AirTrail

docker container

### AirTrail Version

v2.1.1

### Your docker-compose.yml content

```YAML
running this in kubernetes using a custom helm chart, values:

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/common-3.6.1/charts/library/common/values.schema.json
defaultPodOptions:
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: RuntimeDefault
controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: johly/airtrail
          pullPolicy: IfNotPresent
          tag: v2.1.1
        securityContext:
          # runAsNonRoot: true
          # runAsUser: 10001
          # runAsGroup: 10001
          # allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
        env:
          TZ: America/Los_Angeles
          ORIGIN: "https://airtrail.domain.io"
          DB_URL:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_URL
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_DATABASE_NAME 
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_USERNAME
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    className: traefik
    hosts:
      - host: &host airtrail.domain.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: airtrail-tls
```

### Your .env content

```Shell

```

### Reproduction steps

1. add the routes in order of visit
2. refresh page
3. doesn't show them in order
...

### Relevant log output

```shell

```
