### ISSUE TITLE
Cross-site POST form submissions are forbidden

### ISSUE THREAD

**Issue by 3sky** [johanohly/AirTrail#19]
### The bug

Hi there,
Seems like I have issue with 
`{
  "message": "Cross-site POST form submissions are forbidden"
}`

If I'm running behind revers proxy, with my own private domain. The question to you is what should be a ORGIN value? 
The flow is that Caddy get traffic on airtrail.xzy.cc and over internal docker network deliver it to  container:3000.
For other self-hosted apps it works, here I have an issue with CORS.

I tired:
http://localhost:3000
http://localhost:443
https://airtrail.xzy.cc

### Operating System that is running AirTrail

RHEL 9

### AirTrail Version

latest

### Your docker-compose.yml content

```YAML
---
name: airtrail
---
networks:
  app: {}
  proxy:
    external: true
    name: proxy
---
volumes:
  data: {}
---
services:
  db:
    image: postgres:16-alpine
    restart: always
    networks:
      - app
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrail
      POSTGRES_PASSWORD: {{ airtrail_db_password }}
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airtrail -d airtrail"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    image: johly/airtrail:latest
    restart: always
    environment:
      ORIGIN: http://localhost:443
      DB_URL: postgres://airtrail:{{ airtrail_db_password }}@db:5432/airtrail
    networks:
      - proxy
      - app
    expose:
      - 3000
    depends_on:
      db:
        condition: service_healthy
```

### Reproduction steps

1. Probably hard to reproduce on diffrent setup
2.
3.
...
