### ISSUE TITLE
An unknown error occured - Internal Error

### ISSUE THREAD

**Issue by DKeppi** [johanohly/AirTrail#194]
### The bug

Got following error in the logs:

```
Starting server...

Loaded config from .env

Listening on 0.0.0.0:3000

If bundling, conditions should include development or production. If not bundling, conditions or NODE_ENV should include development or production. See https://www.npmjs.com/package/esm-env for tips on setting conditions in popular bundlers and runtimes.

minute: "numeric"

}).format(date);

const prepareFlightData = (data) => {

if (!data) return [];

return data.map((flight) => {

const departure = flight.departure ? parseLocalizeISO(flight.departure, flight.from.tz) : null;

                                                                                            ^

TypeError: null is not an object (evaluating 'flight.from.tz')

      at /app/build/server/chunks/data.js:33:88

      at map (unknown:1:11)

      at prepareFlightData (/app/build/server/chunks/data.js:31:15)

      at _page (/app/build/server/entries/pages/_page.svelte.js:6454:34)

      at children (/app/build/server/chunks/internal.js:420:9)

      at children (/app/build/server/entries/pages/_layout.svelte.js:11444:13)

      at Tooltip_provider (/app/build/server/chunks/MapLibre.js:6789:3)

      at children (/app/build/server/entries/pages/_layout.svelte.js:11422:9)

      at slot (/app/build/server/chunks/index2.js:352:5)

      at QueryClientProvider (/app/build/server/entries/pages/_layout.svelte.js:69:3)
```

### Operating System that is running AirTrail

Docker Container johly/airtrail

### AirTrail Version

Latest

### Your docker-compose.yml content

```YAML
db:
    image: postgres:16
    container_name: AirTrail-DB
    hostname: AirTrail-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "airtrail", "-U", "airtrailuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /home/airtrail-db:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrailuser
      POSTGRES_PASSWORD: airtrailpass
    restart: on-failure:5

  airtrail:
    image: johly/airtrail:latest
    container_name: AirTrail
    restart: on-failure:5
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - DB_URL=postgres://airtrailuser:airtrailpass@db:5432/airtrail
      - DB_DATABASE_NAME=airtrail
      - DB_USERNAME=airtrailuser
      - DB_PASSWORD=airtrailpass
    ports:
      - 8582:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell

```

### Reproduction steps

Start the Stack with the Airtrail and postgres-DB Containers

### Relevant log output

```shell

```
