### ISSUE TITLE
Can't Import Airtrail Data in CSV format

### ISSUE THREAD

**Issue by switchback028** [johanohly/AirTrail#198]
### The bug

Can't import CSV data into Airtrail using Airtrail export format. I've tracked my flights using a Libreoffice spreadsheet and wanted to try visualizing the data, however importing >200 flights is a bit much so I tried converting over to a CSV. After a few hours I can't get the CSV to import using the Airtrail format. 

### Operating System that is running AirTrail

Debian 12 w/ Docker Compose

### AirTrail Version

v2.0

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrail
      POSTGRES_PASSWORD: SecretPassword
    volumes:
      - /opt/airtrail:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U airtrail -d airtrail']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    environment:
      - ORIGIN=http://URL:3000
      - DB_URL=postgres://airtrail:SecretPassword@db:5432/airtrail
      - DB_PASSWORD=SecretPassword
      - DB_DATABASE_NAME=airtrail
      - DB_USERNAME=airtrail
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell
n/a
```

### Reproduction steps

1. Add two flights manually
2. Export airtrails CSV
3. attempt to import
Error given is "failed to import file"

### Relevant log output

```shell
No errors in docker output.
```

### Additional information

I can add flights manually, however any attempt to import data using Airtrails CSV format fails. JSON format works as expected. As a test I also created a flightradar24 account and tested importing using their format, which succeeds successfully.
