### ISSUE TITLE
Can't access via domain

### ISSUE THREAD

**Issue by giuseppebaldi** [johanohly/AirTrail#202]
### The bug

I have Airtrail set up and some flight information put in. Currently, I can access it via localhost:3050 and it works great. I am attempting to access the application via a custom subdomain flights.mydomain.us. I have several (nearly 30) other containers set up this way that work fine but I cannot get this one to work and I'm driving myself mad trying to figure it out.

### Operating System that is running AirTrail

QNAP NAS

### AirTrail Version

v2.2.0

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3050:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=https://flights.mydomain.us:443

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the "password" part of the URL
# If you are using your own database, you should change this to the correct URL
#                          ∨∨∨∨∨∨∨∨
DB_URL=postgres://airtrail:**********@db:5432/airtrail
#                                   ∧∧
# Change "db" to "localhost" if you are developing locally

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=**********

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Install via Docker Compose per Documentation
2. Set up subdomain to point to localhost:3050
3. visit flights.mydomain.us, get 502 error
...

### Relevant log output

```shell

```

### Additional information

I have tried different configurations of my .env file: including/excluding :443, using domain only without subdomain, using subdomain with domain, and all relevant combinations of the above. For reference I am accessing via Cloudflare tunnel.
