### ISSUE TITLE
API issue

### ISSUE THREAD

**Issue by bepsht01** [johanohly/AirTrail#204]
### The bug

Hi,

I have Airtrail deploy on my Synology. I tried to insert a record via Python script. generate an API key and tried to run it. No matter what i do, i am getting "Unauthorized", even if i copy and past your example (with auth key from my deployment).
My headers look like:
headers = {
  "Authorization": "hsmiyz3buqlyrlz3gfwk43blablablalbla"
}

Not sure where the problem is. Thanks

### Operating System that is running AirTrail

Synology

### AirTrail Version

2.0.0

### Your docker-compose.yml content

```YAML
services:
  db:
    image: postgres:16
    container_name: AirTrail-DB
    hostname: airtrail-db
    mem_limit: 1g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "airtrail", "-U", "airtrailuser"]
      timeout: 45s
      interval: 10s
      retries: 10
    volumes:
      - /volume1/docker/airtraildb:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_DB: airtrail
      POSTGRES_USER: airtrailuser
      POSTGRES_PASSWORD: airtrailpass
    restart: on-failure:5

  airtrail:
    image: johly/airtrail:latest
    container_name: AirTrail
    restart: on-failure:5
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    environment:
      - ORIGIN=https://airtrail.xxxxxx.synology.me
      - DB_URL=postgres://airtrailuser:airtrailpass@db:5432/airtrail
      - DB_DATABASE_NAME=airtrail
      - DB_USERNAME=airtrailuser
      - DB_PASSWORD=airtrailpass
    ports:
      - 3xxxx:3000
    depends_on:
      db:
        condition: service_healthy
```

### Your .env content

```Shell

```

### Reproduction steps

1.
2.
3.
...

### Relevant log output

```shell

```
