### ISSUE TITLE
Mismatching Flight Dates/Day

### ISSUE THREAD

**Issue by faizut4one** [johanohly/AirTrail#208]
### The bug

Entered a flight on Monday, 10th of February 2025 with a return leg on the Thursday 13th of February. In the statistic page, the flight is outbound flight is shown to be occuring on a Tuesday and the return flight on a Friday.

Flight is from KUL to BKI (+8 GMT).

Have tried to set a environment variable TMZ to match +8 GMT but ends up with same result (i.e. statistic page shows all flight occuring 1 day later than what was entered).

### Operating System that is running AirTrail

Docker Compose

### AirTrail Version

2.32.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: unless-stopped
    env_file:
      - stack.env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /mnt/docker-nfs/airtrail/db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: unless-stopped
    networks:
      - DockerNet
      - default
    env_file:
      - stack.env
    depends_on:
      db:
        condition: service_healthy

networks:
  DockerNet:
    external: true
```

### Your .env content

```Shell
ORIGIN=https://airtrail.foo.domain.tld:443
DB_URL=postgres://airtrail:isXff9NZkCl4mn2Uumd17SkEtPcw@db:5432/airtrail
DB_PASSWORD=isXff9NZkCl4mn2Uumd17SkEtPcw
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Enter a flight from KUL - BKI
2. Check the Statistic Page, flight will appear to be offset by +1 day

### Relevant log output

```shell

```
