### ISSUE TITLE
Statistics page doesn't load

### ISSUE THREAD

**Issue by evanrich** [johanohly/AirTrail#218]
### The bug

after updating to v2.2.1 or  v2.2.2 when you click the "statistics page" it doesn't load, just shows the blurred background.  Have to hit refresh in my browser to reload the page to go back.  Going back to v2.2.0 successfully loads the statistics page again.
![Image](https://github.com/user-attachments/assets/539efeb7-7a39-4c42-a5fc-cde40a24395b)

### Operating System that is running AirTrail

Docker container

### AirTrail Version

v2.2.2

### Your docker-compose.yml content

```YAML

```

### Your .env content

```Shell

```

### Reproduction steps

1. Upgrade to v2.2.1 or v.2.2.2
2. click statistics
3. 
...

### Relevant log output

```shell

```

### Additional information

I'm using a generic helm chart to deploy in kubernetes, here is the values file:
```
defaultPodOptions:
  securityContext:
    runAsUser: 10001
    runAsGroup: 10001
    fsGroup: 10001
    fsGroupChangePolicy: "OnRootMismatch"
    seccompProfile:
      type: RuntimeDefault
controllers:
  main:
    strategy: Recreate
    containers:
      main:
        image:
          repository: johly/airtrail
          pullPolicy: IfNotPresent
          tag: v2.2.0
        securityContext:
          # runAsNonRoot: true
          # runAsUser: 10001
          # runAsGroup: 10001
          # allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
        probes:
          liveness:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: http
        env:
          TZ: America/Los_Angeles
          ORIGIN: "https://airtrail.tld.io"
          DB_URL:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_URL
          DB_DATABASE_NAME:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_DATABASE_NAME 
          DB_USERNAME:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_USERNAME
          DB_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: airtrail-secrets
                key: DB_PASSWORD
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
service:
  main:
    controller: main
    ports:
      http:
        port: 3000
ingress:
  main:
    enabled: true
    annotations:
      kubernetes.io/tls-acme: "true"
    className: traefik
    hosts:
      - host: &host airtrail.tld.io
        paths:
          - path: /
            pathType: Prefix
            service:
              identifier: main
              port: http
    tls:
      - hosts:
          - *host
        secretName: airtrail-tls
```
