### ISSUE TITLE
Airtrail requires outbound network access because prisma isn't a prod dependency

### ISSUE THREAD

**Issue by jcgillespie** [johanohly/AirTrail#227]
### The bug

The AirTrail Docker image fails to start if it doesn't have outbound network access. This appears to be due to the `prisma migrate` in the `entrypoint.sh`.  

I found this because I was attempting to put airtrail behind an existing Nginx Proxy Manager instance I have and modified the default networking to isolate airtrail behind that manager instance.

### Operating System that is running AirTrail

Docker on macOS

### AirTrail Version

v2.3.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - default
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
      nginx-proxy-manager:
        condition: service_started
    networks:
      - default
      - nginx_proxy
  nginx-proxy-manager:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    ports:
      - 80:80 # Public HTTP Port
      - 443:443 # Public HTTPS Port
      - 81:81 # Admin Web Port
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - outbound
      - nginx_proxy
volumes:
  db_data:

networks:
  default:
    internal: true
  nginx_proxy:
    internal: true
  outbound: {}
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=http://localhost:3000

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the "password" part of the URL
# If you are using your own database, you should change this to the correct URL
#                          ∨∨∨∨∨∨∨∨
DB_URL=postgres://airtrail:password@db:5432/airtrail
#                                   ∧∧
# Change "db" to "localhost" if you are developing locally

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=password

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Modify the default compose file to put the airtrail service on a network that cannot access the internet
2. docker compose up


### Relevant log output

```shell
[+] Running 1/1
 ✔ Container airtrail  Created                                                                                                                                                                                                                                   0.0s 
Attaching to airtrail
airtrail  | Applying migrations...
airtrail  | Resolving dependencies
airtrail  | Resolved, downloaded and extracted [6]
airtrail  | error: ConnectionRefused downloading package manifest prisma
airtrail  | Starting server...
airtrail  | Error loading app config from .env: 540 |         result = new this._Promise((resolve, reject) => {
airtrail  | 541 |           query.callback = (err, res) => (err ? reject(err) : resolve(res))
airtrail  | 542 |         }).catch((err) => {
airtrail  | 543 |           // replace the stack trace that leads to `TCP.onStreamRead` with one that leads back to the
airtrail  | 544 |           // application that created the query
airtrail  | 545 |           Error.captureStackTrace(err)
airtrail  |                       ^
airtrail  | error: relation "app_config" does not exist
airtrail  |  code: "42P01"
airtrail  | 
airtrail  |       at /app/node_modules/pg/lib/client.js:545:17
airtrail  |       at processTicksAndRejections (native:7:39)
airtrail  |       at /app/node_modules/kysely/dist/esm/dialect/postgres/postgres-driver.js:109:23
airtrail  |       at processTicksAndRejections (native:7:39)
airtrail  | 
airtrail exited with code 0
```

### Additional information

_No response_
