### ISSUE TITLE
Can't create account

### ISSUE THREAD

**Issue by Sammeeeeeeee** [johanohly/AirTrail#66]
### The bug

When i go to the web interface, when trying to create the account, it i just get the spinning icon.

### Operating System that is running AirTrail

Ubuntu 24.04 LTS (Docker)

### AirTrail Version

v0.3.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 8616:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
ORIGIN=http://localhost:8613
DB_URL=postgres://airtrail:SuperSecurePassword@db:5432/airtrail
DB_PASSWORD=SuperSecurePassword
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Pull latest image
2. `docker compose up -d`
3. Navigate to the website 
4. Try create acccount 
5.Button state remains in spinny mode

### Relevant log output

```shell
Found this in the console:

entry.EVOLsRX8.js:1 
        
        
        POST http://192.168.0.5:8616/api/users/setup 403 (Forbidden)
window.fetch @ entry.EVOLsRX8.js:1
n @ spring.CpRWHAol.js:8
spring.CpRWHAol.js:9  Uncaught (in promise) {message: 'Cross-site POST form submissions are forbidden'}
Kt @ spring.CpRWHAol.js:9
await in Kt
n @ spring.CpRWHAol.js:8
```
```


### Additional information

_No response_
