### ISSUE TITLE
Incorrect offset calculations for some combinations of airports

### ISSUE THREAD

**Issue by nirenjan** [johanohly/AirTrail#70]
### The bug

When trying to add a flight from VOMM/MAA to OMDB/DXB, the UI does not let me add the entry, giving me the following error, however, Dubai time 0620 is well after Chennai 0330.

![image](https://github.com/user-attachments/assets/91b9e0f4-c568-471f-aa0d-c9bb33987cc7)

As a result of the above, I'm forced to enter an arrival date that is later than the actual date, and it calculates the duration incorrectly as below, whereas it should only be a 3-ish hour flight.

![image](https://github.com/user-attachments/assets/553f8269-24e0-4a25-8a74-5520e6105135)

### Operating System that is running AirTrail

Docker

### AirTrail Version

v0.3.1

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  airtrail:
    container_name: airtrail
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 1380:3000
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
# You might have to add :443 if you are using https through a reverse proxy
ORIGIN=http://10.0.0.100:1380

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the PASSWORD_HERE
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:XXXXXXXX@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=XXXXXXXX

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Add flight from VOMM to OMDB, for any date, but use origin time as 0330, and destination time as 0620
2. Save flight, and you will see the error

### Additional information

I attempted to use arrival time in Dubai as 1320, resulting in a flight time of 20 minutes. It seems like some time zone information for the airports is incorrect.

![image](https://github.com/user-attachments/assets/562e05e6-bfdc-42aa-9578-3dc23377eb04)
