### ISSUE TITLE
Cross-site POST form submissions are forbidden

### ISSUE THREAD

**Issue by savvasdalkitsis** [johanohly/AirTrail#9]
### The bug

I am seeing a CORS issue during setup despite my ORIGIN environment being set correctly

### Operating System that is running AirTrail

Ubuntu

### AirTrail Version

latest

### Your docker-compose.yml content

```YAML
flights:
    container_name: flights
    environment:
      DB_PASSWORD: XXXX
      DB_URL: postgres://flights:XXX@postgres:5432/flights
      ORIGIN: https://flights.DOMAIN
      PGID: "1000"
      PUID: "1000"
      TZ: Europe/London
    image: johly/airtrail:latest
    labels:
      flame.icon: airplane
      flame.name: flights
      flame.type: application
      flame.url: https://flights.DOMAIN
      traefik.enable: "true"
      traefik.http.routers.flights.entrypoints: websecure
      traefik.http.routers.flights.middlewares: chain-oauth@file
      traefik.http.routers.flights.rule: Host(`flights.DOMAIN`)
      traefik.http.routers.flights.service: flights
      traefik.http.routers.flights.tls: "true"
      traefik.http.routers.flights.tls.certresolver: cloudflare
      traefik.http.routers.flights.tls.domains[0].main: DOMAIN
      traefik.http.routers.flights.tls.domains[0].sans: '*.DOMAIN'
      traefik.http.services.flights.loadbalancer.server.port: "3000"
    restart: unless-stopped
```

### Reproduction steps

I can verify, by attaching to the container, that the environment variable `ORIGIN` was set correctly to my public domain i am serving the app on
