### ISSUE TITLE
Unable to add/update flights departing between 00:00 and 00:59

### ISSUE THREAD

**Issue by wilcochris** [johanohly/AirTrail#95]
### The bug

When going to update certain flights or add certain flights, the developer console gives a 500 error and the docker logs give errors about Invalid Dates. This only appears to happen if the flight is departing between 00:00 and 00:59

### Operating System that is running AirTrail

Windows

### AirTrail Version

v1.0.0

### Your docker-compose.yml content

```YAML
services:
  db:
    container_name: airtrail_db
    image: postgres:16-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - /srv/volumes/airtrail_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
  airtrail:
    container_name: airtrail_app
    image: johly/airtrail:latest
    restart: always
    env_file:
      - .env
    ports:
      - 3400:3000
    depends_on:
      db:
        condition: service_healthy

#volumes:
#  db_data:
```

### Your .env content

```Shell
# Your domain, e.g https://example.com
ORIGIN=https://###

# The database URL used by the application.
# If you are using the provided docker-compose file, you should only change the PASSWORD_HERE
# If you are using your own database, you should change this to the correct URL
DB_URL=postgres://airtrail:###@db:5432/airtrail

# Values below this line are only for the default provided postgres database
###################################################################################
# Connection secret for postgres. You should change it to a random password
# Please use only the characters `A-Za-z0-9`, without special characters or spaces
# When you change the DB_PASSWORD, you should also update the DB_URL accordingly
DB_PASSWORD=###

# The values below this line do not need to be changed
###################################################################################
DB_DATABASE_NAME=airtrail
DB_USERNAME=airtrail
```

### Reproduction steps

1. Select flight VJ972
2. Update the relevant date and time of departure/arrival (18/10/2024 @ 00:21, 18/10/2024 @ 05:32)
3. Click save
4. Check the developer console and see that it gives a 500 error
5. Check Docker logs for the issue (see log output)
6. Go back and add a random flight (FR12 in this case)
7. Click search and set a random date and time and then click save (26/11/2024 @ 00:21, 26/11/2024 @ 02:32)
10. Check the developer console and see that it gives a 500 error
11. Check Docker logs for the issue (same log output below)
12. Go back and add another random flight (FR12 in this instance)
13. Click search and set a random date and time and then click save (26/11/2024 @ 01:21, 26/11/2024 @ 02:32)
14. Flight saves just fine

### Relevant log output

```shell
RangeError: Invalid Date

      at toISOString (/app/node_modules/@date-fns/tz/date/index.js:30:26)

      at /app/build/server/entries/endpoints/api/flight/save/_server.ts.js:92:45

25 |   //#region representation

26 | 

27 |   toISOString() {

28 |     const [sign, hours, minutes] = this.tzComponents();

29 |     const tz = `${sign}${hours}:${minutes}`;

30 |     return this.internal.toISOString().slice(0, -1) + tz;
```

### Additional information

I will add that 3 other flights I've had to update have updated just fine (LHR-DEL updated with the correct times. HAN-DEL updated with the correct times. DEL-HAN doesn't update and gives the 500 error).

If I change the timings of VJ972 to be 01:21 (Dep) it will save just fine

https://snipboard.io/meXlOS.jpg - unable to update flight
https://snipboard.io/U0BRtz.jpg - random flight info (The timings of this give the same 500 error)
https://snipboard.io/mbBVkT.jpg - random flight info (with different times)
https://snipboard.io/kdyqCU.jpg - random flight added
